# Generated by Django 3.2 on 2024-06-18 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='naira', max_length=255)),
                ('currency_type', models.CharField(default='fiat', max_length=255)),
                ('crypto_amount', models.FloatField(default=0.0)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction_type', models.CharField(max_length=255, null=True)),
                ('transaction_hash', models.CharField(max_length=255, null=True)),
                ('wallet_address', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('biller_code', models.CharField(blank=True, max_length=255, null=True)),
                ('item_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='NG', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
