version: '3.7'

services:
  web:
    container_name: django
    build: .
    # command: gunicorn --bind :8000 --workers 3 BinanceGift.wsgi:application
    # command:  python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000

  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./Logs:/var/log/nginx
    depends_on:
      - web
