version: '3.7'

services:
  web:
    container_name: django
    build: .
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
    expose:
      - 8000
    env_file:
      - "~/bitgifty/.env"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn --bind :8000 --workers 3 BinanceGift.wsgi:application"

  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./Logs:/var/log/nginx
      - staticfiles:/web/static
    depends_on:
      - web

volumes:
  staticfiles:  # <-- declare the static volume
