# Generated by Django 3.2 on 2023-07-18 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0004_auto_20230718_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_currency', models.CharField(max_length=255)),
                ('second_currency', models.CharField(max_length=255)),
                ('factor', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_from_amount', models.FloatField(default=0.0)),
                ('swap_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_from', to='wallets.wallet')),
                ('swap_table', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swap.swaptable')),
                ('swap_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_to', to='wallets.wallet')),
            ],
        ),
    ]
