# Generated by Django 3.2 on 2023-07-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0002_auto_20230719_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swap',
            old_name='swap_from_amount',
            new_name='swap_amount',
        ),
    ]
