# Generated by Django 3.2 on 2023-07-23 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0003_rename_swap_from_amount_swap_swap_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swap',
            name='swap_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swap.swaptable'),
        ),
    ]
