# Generated by Django 3.2 on 2023-07-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0005_auto_20230728_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdtprice',
            name='coin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
