# Generated by Django 3.2 on 2023-07-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0006_usdtprice_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='swap_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
