# Generated by Django 3.2 on 2024-06-26 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EVCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EVItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('old_price', models.CharField(blank=True, max_length=50, null=True)),
                ('new_price', models.CharField(blank=True, max_length=50, null=True)),
                ('banner', models.CharField(blank=True, max_length=255, null=True)),
                ('display_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('menu', models.CharField(blank=True, max_length=255, null=True)),
                ('star', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EVItemCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('new_price', models.CharField(max_length=50)),
                ('star', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EVStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('thumbnail', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('banner', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('delivery_time', models.CharField(max_length=50)),
                ('delivery_fee', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(related_name='stores', to='ev.EVCategory')),
            ],
        ),
        migrations.CreateModel(
            name='EVSuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('store', models.ManyToManyField(related_name='super', to='ev.EVStore')),
            ],
        ),
        migrations.CreateModel(
            name='EVShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EVOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemOrder', models.ManyToManyField(related_name='orders', to='ev.EVItemCart')),
            ],
        ),
        migrations.CreateModel(
            name='EVOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('orders', models.ManyToManyField(related_name='items', to='ev.EVOrderItem')),
                ('shippingAddress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='ev.evshippingaddress')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='evcategory',
            name='items',
            field=models.ManyToManyField(related_name='categories', to='ev.EVItem'),
        ),
    ]
