# Generated by Django 3.2 on 2024-07-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ev', '0002_auto_20240703_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evcategory',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='categories', to='ev.EVItem'),
        ),
        migrations.AlterField(
            model_name='evcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='banner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='stores', to='ev.EVCategory'),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='cutoff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='delivery_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evsupercategory',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evsupercategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evsupercategory',
            name='store',
            field=models.ManyToManyField(blank=True, null=True, related_name='super', to='ev.EVStore'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.            A user will get all permissions granted to each of their groups.', related_name='ev_users', related_query_name='ev_user', to='auth.Group'),
        ),
    ]
