# Generated by Django 3.2 on 2024-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0003_auto_20240705_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcategory',
            name='items',
            field=models.ManyToManyField(related_name='categories', to='ev.EVItem'),
        ),
        migrations.AlterField(
            model_name='evstore',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='stores', to='ev.EVCategory'),
        ),
        migrations.AlterField(
            model_name='evsupercategory',
            name='store',
            field=models.ManyToManyField(blank=True, related_name='super', to='ev.EVStore'),
        ),
    ]
