# Generated by Django 3.2 on 2023-07-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20230102_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='wallet',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='asset',
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='naira', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_type',
            field=models.CharField(default='fiat', max_length=255),
        ),
    ]
