# Generated by Django 3.2 on 2023-01-25 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='mnemonic',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='network',
            field=models.CharField(blank=True, choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('BNB', 'BNB'), ('CELO', 'CELO'), ('Tron', 'Tron')], max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='xpub',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('owner', 'network')},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
    ]
