# Generated by Django 3.2 on 2023-01-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20230125_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='qrcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
