# Generated by Django 3.2 on 2023-07-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_wallet_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='network',
            field=models.CharField(blank=True, choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('BNB', 'BNB'), ('CELO', 'CELO'), ('Tron', 'Tron'), ('Naira', 'Naira')], max_length=555, null=True),
        ),
    ]
