# Generated by Django 3.2 on 2023-08-12 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plan_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diso_name', models.CharField(max_length=255)),
                ('disco_id', models.IntegerField(default=0)),
                ('plan_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plan_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='datapurchase',
            name='network',
        ),
        migrations.AddField(
            model_name='airtimepurchase',
            name='token_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cablepurchase',
            name='token_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='datapurchase',
            name='token_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='electricitypurchase',
            name='token_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField(default=0)),
                ('plan_type', models.CharField(max_length=255)),
                ('plan_name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('validity', models.CharField(max_length=255)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.network')),
            ],
        ),
        migrations.AlterField(
            model_name='airtimepurchase',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.network'),
        ),
        migrations.AlterField(
            model_name='datapurchase',
            name='data_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.dataplan'),
        ),
        migrations.AlterField(
            model_name='electricitypurchase',
            name='disco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.disco'),
        ),
    ]
