# Generated by Django 3.2 on 2023-08-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_auto_20230812_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='CablePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField(default=0)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.cable')),
            ],
        ),
        migrations.AlterField(
            model_name='cablepurchase',
            name='cable_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.cableplan'),
        ),
    ]
