# Generated by Django 3.2 on 2023-08-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_auto_20230812_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disco',
            old_name='diso_name',
            new_name='disco_name',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='disco_id',
        ),
    ]
