# Generated by Django 3.2 on 2023-08-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0005_auto_20230812_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtimepurchase',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='cablepurchase',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='datapurchase',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='electricitypurchase',
            name='wallet',
        ),
        migrations.AddField(
            model_name='airtimepurchase',
            name='wallet_from',
            field=models.CharField(default='naira', max_length=255),
        ),
        migrations.AddField(
            model_name='airtimepurchase',
            name='wallet_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cablepurchase',
            name='wallet_from',
            field=models.CharField(default='naira', max_length=255),
        ),
        migrations.AddField(
            model_name='cablepurchase',
            name='wallet_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datapurchase',
            name='wallet_from',
            field=models.CharField(default='naira', max_length=255),
        ),
        migrations.AddField(
            model_name='datapurchase',
            name='wallet_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electricitypurchase',
            name='wallet_from',
            field=models.CharField(default='naira', max_length=255),
        ),
        migrations.AddField(
            model_name='electricitypurchase',
            name='wallet_id',
            field=models.IntegerField(default=0),
        ),
    ]
