# Generated by Django 3.2 on 2024-03-23 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dapp', '0004_transaction_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=555, null=True)),
                ('private_key', models.CharField(blank=True, max_length=555, null=True)),
                ('xpub', models.CharField(blank=True, max_length=555, null=True)),
                ('mnemonic', models.CharField(blank=True, max_length=555, null=True)),
                ('network', models.CharField(blank=True, max_length=555, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('qrcode', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dapp_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
