# Generated by Django 3.2 on 2024-03-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0005_adminwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
