# Generated by Django 3.2 on 2024-04-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0006_transaction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='biller_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='item_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
