# Generated by Django 3.2 on 2024-04-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0007_auto_20240404_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bill_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
