# Generated by Django 3.2 on 2024-04-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0008_transaction_bill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=255, unique=True)),
                ('amount', models.FloatField(default=0.0)),
                ('percentage', models.FloatField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=255, unique=True)),
                ('amount', models.FloatField(default=0.25)),
            ],
        ),
    ]
