# Generated by Django 3.2 on 2024-04-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0009_cashback_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='country',
            field=models.CharField(blank=True, default='nigeria', max_length=255),
        ),
    ]
