# Generated by Django 3.2 on 2024-04-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0010_transaction_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.CharField(blank=True, default='nigeria', max_length=255, null=True),
        ),
    ]
