# Generated by Django 3.2 on 2024-06-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0013_alter_transaction_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='short_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
