# Generated by Django 3.2 on 2024-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0014_transaction_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='error_message',
            field=models.TextField(null=True),
        ),
    ]
