# Generated by Django 3.2 on 2024-08-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0015_transaction_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
