# Generated by Django 3.2 on 2024-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0016_transaction_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='StellarTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='naira', max_length=255)),
                ('currency_type', models.CharField(default='fiat', max_length=255)),
                ('crypto_amount', models.FloatField(default=0.0)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction_type', models.CharField(max_length=255, null=True)),
                ('transaction_hash', models.CharField(max_length=255, null=True)),
                ('wallet_address', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('biller_code', models.CharField(blank=True, max_length=255, null=True)),
                ('item_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='NG', max_length=255, null=True)),
                ('short_code', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(null=True)),
                ('token', models.TextField(null=True)),
            ],
        ),
    ]
