# Generated by Django 3.2 on 2024-10-03 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftCards', '0014_alter_giftcardimage_version'),
        ('dapp', '0017_stellartransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemStellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('redemption_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StellarGiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0)),
                ('receipent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='generated', max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='giftCards.giftcardimage')),
            ],
        ),
    ]
