# Generated by Django 3.2 on 2024-11-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0018_redeemstellar_stellargiftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
