# Generated by Django 3.2 on 2022-12-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('fees', models.FloatField(default=0.0)),
                ('binance_code', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypted_code', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet')),
            ],
        ),
    ]
