# Generated by Django 3.2 on 2023-01-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftCards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='giftcard',
            name='status',
            field=models.CharField(default='generated', max_length=255),
        ),
    ]
