# Generated by Django 3.2 on 2023-04-19 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftCards', '0003_auto_20230115_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcard',
            old_name='binance_code',
            new_name='code',
        ),
        migrations.AddField(
            model_name='redeem',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
