# Generated by Django 3.2 on 2023-04-20 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftCards', '0004_auto_20230419_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='encrypted_code',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='giftCards.giftcardimage'),
        ),
    ]
