# Generated by Django 3.2 on 2023-04-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftCards', '0005_auto_20230420_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
