# Generated by Django 3.2 on 2023-05-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftCards', '0007_auto_20230516_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='receipent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
