# Generated by Django 3.2 on 2023-07-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftCards', '0008_giftcard_receipent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardfee',
            name='network',
            field=models.CharField(max_length=255),
        ),
    ]
