name: BitGifty CI-CD
on:
    # Triggers the workflow on push or pull request events but only for the masterii branch
    
    push:
      branches: [master]
    pull_request:
      branches: [master]
    # Run this workflow manually from the Actions tab on Repo homepage
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          # VPS IP
          HOST: ${{ secrets.VPS_SSH_HOST }}       
          # VPS username
          USERNAME: ${{ secrets.VPS_SSH_USERNAME }}
          # SSH key (copy it from your local machine)
          KEY: ${{ secrets.VPS_SSH_SECRET }}
          # SSH port
          PORT: ${{ secrets.VPS_SSH_PORT }}
        with:
          source: "."
          target: "/home/princewill/bitgifty/InvestEasy"
        # with:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.VPS_SSH_HOST }}       
          # VPS username
          USERNAME: ${{ secrets.VPS_SSH_USERNAME }}
          # SSH key (copy it from your local machine)
          KEY: ${{ secrets.VPS_SSH_SECRET }}
          # SSH port
          PORT: ${{ secrets.VPS_SSH_PORT }}
          script: |
            make down
            make build
            echo "Deleting old image(s)..."
            docker image prune -a -f
